version: "3"

services:
  replay-service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - cqrs-practise-network
    ports:
      - "8080:8080"
    depends_on:
      - nats-server
    command: ["/bin/sh", "-c", "/app/app -app=replayservice"]
    volumes:
      - .env.docker:/app/.env:ro

  odds-worker:
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - cqrs-practise-network
    depends_on:
      - nats-server
    command: ["/bin/sh", "-c", "/app/app -app=oddsworker"]
    volumes:
      - .env.docker:/app/.env:ro

  nats-server:
    image: nats:2.9-alpine3.17
    restart: on-failure
    networks:
      - cqrs-practise-network
    ports: 
      - "4222:4222"
      - "8222:8222"

networks:
  cqrs-practise-network:
    name: cqrs-practise-network
